/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ScientistRole;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import userinterface.planterRole.GraphJPanel;

/**
 *
 * @author Ayushkumar
 */
public class Analytics2JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Analytics2JPanel
     */
     JPanel container;
    public Analytics2JPanel(JPanel container) {
        initComponents();
        this.container=container;     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grphButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        barpanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grphButton.setText("show graph");
        grphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grphButtonActionPerformed(evt);
            }
        });
        add(grphButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jButton2.setText("<<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        barpanel.setLayout(new javax.swing.BoxLayout(barpanel, javax.swing.BoxLayout.LINE_AXIS));
        add(barpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 670, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void grphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grphButtonActionPerformed
        // TODO add your handling code here:
        
        {                                         
        
         BufferedReader br= null;
   
             try {
                 // TODO add your handling code here:
                 br = new BufferedReader(new FileReader(new File("science.csv")));
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(GraphJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
        String line;
   DefaultCategoryDataset dcd = new DefaultCategoryDataset();
    try {
        while ((line = br.readLine()) != null)
        {
            String[] entries = line.split(",");
            {
                String year=entries[0];
                
                String prod=entries[1];
                
                String crop=entries[2];
               
                dcd.setValue(Integer.parseInt(prod),(year),crop);
             //   dcd.setValue(Integer.parseInt(prod), "",crop);
               
                
                
//                dcd.setValue(82,"Marks", "Akshat");
//                dcd.setValue(85,"Marks", "Vijay");
//                dcd.setValue(87,"Marks", "Kavya");
//                dcd.setValue(88,"Marks", "Mayank");
//                
               
                
            }
            
    }                                        
    } catch (IOException ex) {
        Logger.getLogger(GraphJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
     JFreeChart jchart =ChartFactory.createBarChart("Year","Crop" ,"Production", dcd, PlotOrientation.VERTICAL, true, true, false);
                CategoryPlot cplot= jchart.getCategoryPlot();
                cplot.setRangeGridlinePaint(Color.BLUE);
                
                ChartFrame cframe=new ChartFrame("Crop usage",jchart,true);
                
                ChartPanel cpanel=new ChartPanel(jchart);
                
                
                barpanel.add(cpanel);
                barpanel.updateUI();
    
    }
        
                                            
    }//GEN-LAST:event_grphButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        container.remove(this);
       CardLayout layout = (CardLayout) container.getLayout();
       layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barpanel;
    private javax.swing.JButton grphButton;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
