/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FundOrganizerRole;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;
import sun.nio.cs.ext.IBM037;
import userinterface.planterRole.GraphJPanel;

/**
 *
 * @author AyushKumar
 */
public class AnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyticsJPanel
     */
    JPanel container;

    
    public AnalyticsJPanel(JPanel container) {
        initComponents();
        this.container = container;
        populate();

    }
    public void populate(){
   BufferedReader br= null;
   
             try {
                 // TODO add your handling code here:
                 br = new BufferedReader(new FileReader(new File("market.csv")));
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(GraphJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
        String line;
   DefaultTableModel model = (DefaultTableModel)tblAnalytics.getModel();
           model.setRowCount(0);

    try {
        while ((line = br.readLine()) != null)
        {
            Object[] entry = line.split(",");
            model.addRow(entry);
            
        }
    }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalytics = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtPopularity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MARKET CONTROL");

        tblAnalytics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crop", "Popularity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnalytics);
        if (tblAnalytics.getColumnModel().getColumnCount() > 0) {
            tblAnalytics.getColumnModel().getColumn(0).setResizable(false);
            tblAnalytics.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setText("<<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPopularity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPopularityActionPerformed(evt);
            }
        });

        jLabel2.setText("Popularity:");

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtPopularity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopularity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAnalytics.getSelectedRow();
        int newVal;
        try{
        newVal = Integer.parseInt(txtPopularity.getText());
        }catch(Exception e){
            // throw erro
            JOptionPane.showMessageDialog(null, "Value needs to be a number");
            return;
        }
        if(selectedRow!=-1){
            Object[] newRow = new Object[2];
            newRow[0] = tblAnalytics.getModel().getValueAt(selectedRow, 0);
            newRow[1] = newVal;
            tblAnalytics.getModel().setValueAt(newVal, selectedRow, 1);
            populateCsv();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPopularityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPopularityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPopularityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnalytics;
    private javax.swing.JTextField txtPopularity;
    // End of variables declaration//GEN-END:variables

    private void populateCsv() {
        File f = new File("/Users/kavyaprakash/Desktop/Final Project/Latest/Upswing04DeccropData/Upswing04DeccropData/market.csv");
        f.delete();
        try{
        f.createNewFile();

        BufferedWriter bw = new BufferedWriter(new FileWriter(f));
        for (int i=0;i<tblAnalytics.getRowCount();++i){
            String crop = String.valueOf(tblAnalytics.getModel().getValueAt(i, 0));
            String popularity = String.valueOf(tblAnalytics.getModel().getValueAt(i, 1));
            bw.write(crop + "," + popularity+'\n');
        }
        
        bw.close();
        
        
        }catch(Exception e){
            
        }
    }
}
