/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FarmerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mayank
 */
public class FarmerDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form FarmerDashBoard
     */
    JPanel userProcessContainer;
    UserAccount account;
    FarmerOrganization farmerOrganization;
    Enterprise enterprise;
    EcoSystem business;
    

    public FarmerDashBoard(JPanel userProcessContainer, UserAccount account, FarmerOrganization farmerOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.farmerOrganization = farmerOrganization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSellCrop = new javax.swing.JButton();
        btnAnsCummQues = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuyroducts = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnSellCrop.setText("Sell My Crop");
        btnSellCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellCropActionPerformed(evt);
            }
        });

        btnAnsCummQues.setText("Answer Community Question");
        btnAnsCummQues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnsCummQuesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Farmer Work Area");

        btnBuyroducts.setText("Buy Products");
        btnBuyroducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyroductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSellCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnsCummQues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuyroducts, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSellCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnsCummQues, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyroducts, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellCropActionPerformed
        // TODO add your handling code here:
        SellMyCrop panel = new SellMyCrop(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("SellMyCrop", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSellCropActionPerformed

    private void btnAnsCummQuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnsCummQuesActionPerformed
        // TODO add your handling code here:
        FarmerWorkAreaJPanel panel = new FarmerWorkAreaJPanel(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("FarmerWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnsCummQuesActionPerformed

    private void btnBuyroductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyroductsActionPerformed
        // TODO add your handling code here:
        buyProducts panel = new buyProducts(userProcessContainer,  account,  farmerOrganization,  enterprise, business);
        userProcessContainer.add("buyProducts", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBuyroductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnsCummQues;
    private javax.swing.JButton btnBuyroducts;
    private javax.swing.JButton btnSellCrop;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
